baseURL = 'https://kmxtaylor.github.io/wwuagic/'
languageCode = 'en-us'
title = 'WWU Association for Gender Inclusion in Computing'
theme = 'roxo-hugo'
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About Us"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Get in Touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  mainLogo = "images/agic-logo-with-name.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Official website of the Western Washington University Association for Gender Inclusion in Computing"
  author = "Katie Taylor (AGIC)"
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  
  # Banner Section
  [params.banner]
    enable                = true
    # background_image      = "images/backgrounds/colorful-background.png"
    # background_image      = "images/backgrounds/basic-background.png"
    background_image      = "images/backgrounds/basic-background2.png"
    # background_image      = "images/backgrounds/basic-background3.png"
    heading               = "WWU Association for Gender Inclusion in Computing"
    # tagline               = "Support gender diversity in computer science!"
    primary_button        = "Connect with Us"
    primary_button_url    = "contact"
    secondary_button      = "About Us"
    secondary_button_url  = "about"

  [params.footer]
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Contact Us"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/wwuagic/"